#!/usr/bin/env bash

if [[ ! "$(ls -A /gbdb)" ]] && [[ "$DBDBID" == "putExampleDbdbidHere" ]]; then
  echo "no genome data found in /gbdb, downloading example data..."
  wget -r -np -e robots=off -nH --cut-dirs=3 -R 'html' -R '\?C=' \
   http://www.bio.fsu.edu/~dvera/share/cruise/gbdb
else
  sleep 5
fi
