#!/bin/bash


# echo "processing genomes"
# cols=$(head -n 1 /tmp/dbDb.tsv)
# tail -n+2 /tmp/dbDb.tsv | while IFS=$'\t' read -r $cols
# do
#   if [ $active -eq 1 ]; then
#     if [[ $(hostname) == $nBlatHost ]] && [[ $nBlatPort != "NA" ]]; then
#       echo "starting nucleotide blat service for $name"
#       gfServer -tileSize=7 -canStop start $(hostname).$DOMAIN $nBlatPort -stepSize=5 $nibPath/genome.2bit &
#     fi
#
#     if [[ $(hostname) == $pBlatHost ]] && [[ $pBlatPort != "NA" ]]; then
#       echo "starting protein blat service for $name"
#       gfServer -trans -canStop start $(hostname).$DOMAIN $pBlatPort $nibPath/genome.2bit &
#     fi
#   fi
# done

pkill gfServer || :

get_dbdb

echo "processing genomes"
cols=$(head -n 1 /tmp/dbDb.tsv)
tail -n+2 /tmp/dbDb.tsv | while IFS=$'\t' read -r $cols
do
  if [ $active -eq 1 ]; then
    if [[ $(hostname) == $nBlatHost ]] && [[ $nBlatPort != "NA" ]]; then
      echo "starting nucleotide blat service for $name"
      gfServer -tileSize=7 -canStop start $(hostname).$DOMAIN $nBlatPort -stepSize=5 $nibPath/genome.2bit &
    fi

    if [[ $(hostname) == $pBlatHost ]] && [[ $pBlatPort != "NA" ]]; then
      echo "starting protein blat service for $name"
      gfServer -trans -canStop start $(hostname).$DOMAIN $pBlatPort $nibPath/genome.2bit &
    fi
  fi
done
