#!/usr/bin/env bash

echo "starting browser refresh..."

# create .hg.conf for access to mysql server
update_perms

# check if fresh install configured for example data
get_example_data

# download dbDb spreadsheet
get_dbdb

# wait for connection to mysql server
check_sql

update_dbDb
update_clade
update_defaultDb
update_genomeClade
update_blatServers
update_genomes
update_liftOverChain


# clear hgcentral
echo "deleting disposable hgcentral tables"
hgsql -e "delete from hgcentral.dbDbArch"
hgsql -e "delete from hgcentral.hubPublic"
hgsql -e "delete from hgcentral.targetDb"
#hgsql -e "delete from hgcentral.hubStatus"
